---
- hosts: all
  become: yes
  tasks:
    - copy:
        content: "Goodluck for ex447"
        dest: /tmp/abc.txt
      notify: Restart appache
  handlers:
    - name: Restart appache
      service:
        name: httpd
        state: restarted
        enabled: yes
