---
- name: Create handlers
  hosts: all
  become: yes
  tasks:
    - name: Content update
      copy:
        content: "Baba Smart Hai"
        dest: /tmp/baba.txt
      notify: update_file

  handlers:
    - name: update_file
      service:
        name: httpd
        state: restarted
        enabled: yes
