---
- name: Create handlers
  hosts: all
  become: yes
  tasks:
    - copy:
        content: "goodluck ex447"
        dest: /tmp/test-handler.txt
      notify: Restart appache
  handlers:
    - name: Restart appache
      service:
        name: httpd
        state: restarted
        enabled: yes 
