---
- name: create handlers
  hosts: all
  become: yes
  tasks:
    - copy:
        content: "goodluck for ex447"
        dest: /tmp/test5.txt
      notify: Restart appache
  handlers:
    - name: Restart appache
      service:
        name: httpd
        state: restarted
        enabled: yes 
