---
- name: Create handlers
  hosts: all
  become: no
  tasks:
    - name: update the file
      copy:
        content: "Baba mathsun hai"
        dest: /tmp/baba.txt
      notify: start_httpd

  handlers:
    - name: start_httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
        
