---
- hosts: all
  become: yes
  tasks:
          - copy:
              content: "Mangal Singh RHCA 2021"
              dest: /tmp/abc.txt
            notify: Restart appache
  handlers:
          - name: Restart appache
            service:
              name: httpd
              state: restarted
              enable: yes
             
...
